version: "3.7"
services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - '4000:4000'
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    container_name: resuelve-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prueba_resuelve_elixir
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_NAME: mysql
